[MeterBar0]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=(5*1.14)R
Y=202
Shape=Rectangle 0,0,(8*1.14),(-(202-(8*1.14))*[MeasureAudioSmoothed0]-(8*1.14)),((8*1.14)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar1]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=(5*1.14)R
Y=202
Shape=Rectangle 0,0,(8*1.14),(-(202-(8*1.14))*[MeasureAudioSmoothed1]-(8*1.14)),((8*1.14)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar2]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=(5*1.14)R
Y=202
Shape=Rectangle 0,0,(8*1.14),(-(202-(8*1.14))*[MeasureAudioSmoothed2]-(8*1.14)),((8*1.14)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar3]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=(5*1.14)R
Y=202
Shape=Rectangle 0,0,(8*1.14),(-(202-(8*1.14))*[MeasureAudioSmoothed3]-(8*1.14)),((8*1.14)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar4]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=(5*1.14)R
Y=202
Shape=Rectangle 0,0,(8*1.14),(-(202-(8*1.14))*[MeasureAudioSmoothed4]-(8*1.14)),((8*1.14)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar5]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=(5*1.14)R
Y=202
Shape=Rectangle 0,0,(8*1.14),(-(202-(8*1.14))*[MeasureAudioSmoothed5]-(8*1.14)),((8*1.14)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar6]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=(5*1.14)R
Y=202
Shape=Rectangle 0,0,(8*1.14),(-(202-(8*1.14))*[MeasureAudioSmoothed6]-(8*1.14)),((8*1.14)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar7]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=(5*1.14)R
Y=202
Shape=Rectangle 0,0,(8*1.14),(-(202-(8*1.14))*[MeasureAudioSmoothed7]-(8*1.14)),((8*1.14)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar8]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=(5*1.14)R
Y=202
Shape=Rectangle 0,0,(8*1.14),(-(202-(8*1.14))*[MeasureAudioSmoothed8]-(8*1.14)),((8*1.14)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar9]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=(5*1.14)R
Y=202
Shape=Rectangle 0,0,(8*1.14),(-(202-(8*1.14))*[MeasureAudioSmoothed9]-(8*1.14)),((8*1.14)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar10]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=(5*1.14)R
Y=202
Shape=Rectangle 0,0,(8*1.14),(-(202-(8*1.14))*[MeasureAudioSmoothed10]-(8*1.14)),((8*1.14)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar11]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=(5*1.14)R
Y=202
Shape=Rectangle 0,0,(8*1.14),(-(202-(8*1.14))*[MeasureAudioSmoothed11]-(8*1.14)),((8*1.14)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar12]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=(5*1.14)R
Y=202
Shape=Rectangle 0,0,(8*1.14),(-(202-(8*1.14))*[MeasureAudioSmoothed12]-(8*1.14)),((8*1.14)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar13]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=(5*1.14)R
Y=202
Shape=Rectangle 0,0,(8*1.14),(-(202-(8*1.14))*[MeasureAudioSmoothed13]-(8*1.14)),((8*1.14)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar14]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=(5*1.14)R
Y=202
Shape=Rectangle 0,0,(8*1.14),(-(202-(8*1.14))*[MeasureAudioSmoothed14]-(8*1.14)),((8*1.14)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar15]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=(5*1.14)R
Y=202
Shape=Rectangle 0,0,(8*1.14),(-(202-(8*1.14))*[MeasureAudioSmoothed15]-(8*1.14)),((8*1.14)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar16]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=(5*1.14)R
Y=202
Shape=Rectangle 0,0,(8*1.14),(-(202-(8*1.14))*[MeasureAudioSmoothed16]-(8*1.14)),((8*1.14)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar17]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=(5*1.14)R
Y=202
Shape=Rectangle 0,0,(8*1.14),(-(202-(8*1.14))*[MeasureAudioSmoothed17]-(8*1.14)),((8*1.14)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar18]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=(5*1.14)R
Y=202
Shape=Rectangle 0,0,(8*1.14),(-(202-(8*1.14))*[MeasureAudioSmoothed18]-(8*1.14)),((8*1.14)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar19]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=(5*1.14)R
Y=202
Shape=Rectangle 0,0,(8*1.14),(-(202-(8*1.14))*[MeasureAudioSmoothed19]-(8*1.14)),((8*1.14)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar20]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=(5*1.14)R
Y=202
Shape=Rectangle 0,0,(8*1.14),(-(202-(8*1.14))*[MeasureAudioSmoothed20]-(8*1.14)),((8*1.14)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar21]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=(5*1.14)R
Y=202
Shape=Rectangle 0,0,(8*1.14),(-(202-(8*1.14))*[MeasureAudioSmoothed21]-(8*1.14)),((8*1.14)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar22]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=(5*1.14)R
Y=202
Shape=Rectangle 0,0,(8*1.14),(-(202-(8*1.14))*[MeasureAudioSmoothed22]-(8*1.14)),((8*1.14)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar23]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=(5*1.14)R
Y=202
Shape=Rectangle 0,0,(8*1.14),(-(202-(8*1.14))*[MeasureAudioSmoothed23]-(8*1.14)),((8*1.14)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar24]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=(5*1.14)R
Y=202
Shape=Rectangle 0,0,(8*1.14),(-(202-(8*1.14))*[MeasureAudioSmoothed24]-(8*1.14)),((8*1.14)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar25]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=(5*1.14)R
Y=202
Shape=Rectangle 0,0,(8*1.14),(-(202-(8*1.14))*[MeasureAudioSmoothed25]-(8*1.14)),((8*1.14)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar26]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=(5*1.14)R
Y=202
Shape=Rectangle 0,0,(8*1.14),(-(202-(8*1.14))*[MeasureAudioSmoothed26]-(8*1.14)),((8*1.14)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar27]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=(5*1.14)R
Y=202
Shape=Rectangle 0,0,(8*1.14),(-(202-(8*1.14))*[MeasureAudioSmoothed27]-(8*1.14)),((8*1.14)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar28]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=(5*1.14)R
Y=202
Shape=Rectangle 0,0,(8*1.14),(-(202-(8*1.14))*[MeasureAudioSmoothed28]-(8*1.14)),((8*1.14)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar29]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=(5*1.14)R
Y=202
Shape=Rectangle 0,0,(8*1.14),(-(202-(8*1.14))*[MeasureAudioSmoothed29]-(8*1.14)),((8*1.14)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar30]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=(5*1.14)R
Y=202
Shape=Rectangle 0,0,(8*1.14),(-(202-(8*1.14))*[MeasureAudioSmoothed30]-(8*1.14)),((8*1.14)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar31]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=(5*1.14)R
Y=202
Shape=Rectangle 0,0,(8*1.14),(-(202-(8*1.14))*[MeasureAudioSmoothed31]-(8*1.14)),((8*1.14)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar32]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=(5*1.14)R
Y=202
Shape=Rectangle 0,0,(8*1.14),(-(202-(8*1.14))*[MeasureAudioSmoothed32]-(8*1.14)),((8*1.14)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar33]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=(5*1.14)R
Y=202
Shape=Rectangle 0,0,(8*1.14),(-(202-(8*1.14))*[MeasureAudioSmoothed33]-(8*1.14)),((8*1.14)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar34]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=(5*1.14)R
Y=202
Shape=Rectangle 0,0,(8*1.14),(-(202-(8*1.14))*[MeasureAudioSmoothed34]-(8*1.14)),((8*1.14)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar35]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=(5*1.14)R
Y=202
Shape=Rectangle 0,0,(8*1.14),(-(202-(8*1.14))*[MeasureAudioSmoothed35]-(8*1.14)),((8*1.14)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar36]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=(5*1.14)R
Y=202
Shape=Rectangle 0,0,(8*1.14),(-(202-(8*1.14))*[MeasureAudioSmoothed36]-(8*1.14)),((8*1.14)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar37]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=(5*1.14)R
Y=202
Shape=Rectangle 0,0,(8*1.14),(-(202-(8*1.14))*[MeasureAudioSmoothed37]-(8*1.14)),((8*1.14)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar38]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=(5*1.14)R
Y=202
Shape=Rectangle 0,0,(8*1.14),(-(202-(8*1.14))*[MeasureAudioSmoothed38]-(8*1.14)),((8*1.14)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar39]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=(5*1.14)R
Y=202
Shape=Rectangle 0,0,(8*1.14),(-(202-(8*1.14))*[MeasureAudioSmoothed39]-(8*1.14)),((8*1.14)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar40]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=(5*1.14)R
Y=202
Shape=Rectangle 0,0,(8*1.14),(-(202-(8*1.14))*[MeasureAudioSmoothed40]-(8*1.14)),((8*1.14)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar41]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=(5*1.14)R
Y=202
Shape=Rectangle 0,0,(8*1.14),(-(202-(8*1.14))*[MeasureAudioSmoothed41]-(8*1.14)),((8*1.14)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar42]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=(5*1.14)R
Y=202
Shape=Rectangle 0,0,(8*1.14),(-(202-(8*1.14))*[MeasureAudioSmoothed42]-(8*1.14)),((8*1.14)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar43]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=(5*1.14)R
Y=202
Shape=Rectangle 0,0,(8*1.14),(-(202-(8*1.14))*[MeasureAudioSmoothed43]-(8*1.14)),((8*1.14)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar44]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=(5*1.14)R
Y=202
Shape=Rectangle 0,0,(8*1.14),(-(202-(8*1.14))*[MeasureAudioSmoothed44]-(8*1.14)),((8*1.14)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar45]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=(5*1.14)R
Y=202
Shape=Rectangle 0,0,(8*1.14),(-(202-(8*1.14))*[MeasureAudioSmoothed45]-(8*1.14)),((8*1.14)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar46]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=(5*1.14)R
Y=202
Shape=Rectangle 0,0,(8*1.14),(-(202-(8*1.14))*[MeasureAudioSmoothed46]-(8*1.14)),((8*1.14)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar47]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=(5*1.14)R
Y=202
Shape=Rectangle 0,0,(8*1.14),(-(202-(8*1.14))*[MeasureAudioSmoothed47]-(8*1.14)),((8*1.14)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar48]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=(5*1.14)R
Y=202
Shape=Rectangle 0,0,(8*1.14),(-(202-(8*1.14))*[MeasureAudioSmoothed48]-(8*1.14)),((8*1.14)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar49]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=(5*1.14)R
Y=202
Shape=Rectangle 0,0,(8*1.14),(-(202-(8*1.14))*[MeasureAudioSmoothed49]-(8*1.14)),((8*1.14)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar50]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=(5*1.14)R
Y=202
Shape=Rectangle 0,0,(8*1.14),(-(202-(8*1.14))*[MeasureAudioSmoothed50]-(8*1.14)),((8*1.14)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar51]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=(5*1.14)R
Y=202
Shape=Rectangle 0,0,(8*1.14),(-(202-(8*1.14))*[MeasureAudioSmoothed51]-(8*1.14)),((8*1.14)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar52]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=(5*1.14)R
Y=202
Shape=Rectangle 0,0,(8*1.14),(-(202-(8*1.14))*[MeasureAudioSmoothed52]-(8*1.14)),((8*1.14)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar53]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=(5*1.14)R
Y=202
Shape=Rectangle 0,0,(8*1.14),(-(202-(8*1.14))*[MeasureAudioSmoothed53]-(8*1.14)),((8*1.14)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar54]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=(5*1.14)R
Y=202
Shape=Rectangle 0,0,(8*1.14),(-(202-(8*1.14))*[MeasureAudioSmoothed54]-(8*1.14)),((8*1.14)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar55]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=(5*1.14)R
Y=202
Shape=Rectangle 0,0,(8*1.14),(-(202-(8*1.14))*[MeasureAudioSmoothed55]-(8*1.14)),((8*1.14)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar56]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=(5*1.14)R
Y=202
Shape=Rectangle 0,0,(8*1.14),(-(202-(8*1.14))*[MeasureAudioSmoothed56]-(8*1.14)),((8*1.14)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar57]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=(5*1.14)R
Y=202
Shape=Rectangle 0,0,(8*1.14),(-(202-(8*1.14))*[MeasureAudioSmoothed57]-(8*1.14)),((8*1.14)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar58]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=(5*1.14)R
Y=202
Shape=Rectangle 0,0,(8*1.14),(-(202-(8*1.14))*[MeasureAudioSmoothed58]-(8*1.14)),((8*1.14)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar59]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=(5*1.14)R
Y=202
Shape=Rectangle 0,0,(8*1.14),(-(202-(8*1.14))*[MeasureAudioSmoothed59]-(8*1.14)),((8*1.14)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar60]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=(5*1.14)R
Y=202
Shape=Rectangle 0,0,(8*1.14),(-(202-(8*1.14))*[MeasureAudioSmoothed60]-(8*1.14)),((8*1.14)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar61]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=(5*1.14)R
Y=202
Shape=Rectangle 0,0,(8*1.14),(-(202-(8*1.14))*[MeasureAudioSmoothed61]-(8*1.14)),((8*1.14)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar62]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=(5*1.14)R
Y=202
Shape=Rectangle 0,0,(8*1.14),(-(202-(8*1.14))*[MeasureAudioSmoothed62]-(8*1.14)),((8*1.14)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar63]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=(5*1.14)R
Y=202
Shape=Rectangle 0,0,(8*1.14),(-(202-(8*1.14))*[MeasureAudioSmoothed63]-(8*1.14)),((8*1.14)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar64]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=(5*1.14)R
Y=202
Shape=Rectangle 0,0,(8*1.14),(-(202-(8*1.14))*[MeasureAudioSmoothed64]-(8*1.14)),((8*1.14)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar65]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=(5*1.14)R
Y=202
Shape=Rectangle 0,0,(8*1.14),(-(202-(8*1.14))*[MeasureAudioSmoothed65]-(8*1.14)),((8*1.14)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar66]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=(5*1.14)R
Y=202
Shape=Rectangle 0,0,(8*1.14),(-(202-(8*1.14))*[MeasureAudioSmoothed66]-(8*1.14)),((8*1.14)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar67]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=(5*1.14)R
Y=202
Shape=Rectangle 0,0,(8*1.14),(-(202-(8*1.14))*[MeasureAudioSmoothed67]-(8*1.14)),((8*1.14)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar68]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=(5*1.14)R
Y=202
Shape=Rectangle 0,0,(8*1.14),(-(202-(8*1.14))*[MeasureAudioSmoothed68]-(8*1.14)),((8*1.14)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar69]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=(5*1.14)R
Y=202
Shape=Rectangle 0,0,(8*1.14),(-(202-(8*1.14))*[MeasureAudioSmoothed69]-(8*1.14)),((8*1.14)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar70]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=(5*1.14)R
Y=202
Shape=Rectangle 0,0,(8*1.14),(-(202-(8*1.14))*[MeasureAudioSmoothed70]-(8*1.14)),((8*1.14)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar71]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=(5*1.14)R
Y=202
Shape=Rectangle 0,0,(8*1.14),(-(202-(8*1.14))*[MeasureAudioSmoothed71]-(8*1.14)),((8*1.14)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar72]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=(5*1.14)R
Y=202
Shape=Rectangle 0,0,(8*1.14),(-(202-(8*1.14))*[MeasureAudioSmoothed72]-(8*1.14)),((8*1.14)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar73]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=(5*1.14)R
Y=202
Shape=Rectangle 0,0,(8*1.14),(-(202-(8*1.14))*[MeasureAudioSmoothed73]-(8*1.14)),((8*1.14)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar74]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=(5*1.14)R
Y=202
Shape=Rectangle 0,0,(8*1.14),(-(202-(8*1.14))*[MeasureAudioSmoothed74]-(8*1.14)),((8*1.14)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar75]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=(5*1.14)R
Y=202
Shape=Rectangle 0,0,(8*1.14),(-(202-(8*1.14))*[MeasureAudioSmoothed75]-(8*1.14)),((8*1.14)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar76]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=(5*1.14)R
Y=202
Shape=Rectangle 0,0,(8*1.14),(-(202-(8*1.14))*[MeasureAudioSmoothed76]-(8*1.14)),((8*1.14)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar77]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=(5*1.14)R
Y=202
Shape=Rectangle 0,0,(8*1.14),(-(202-(8*1.14))*[MeasureAudioSmoothed77]-(8*1.14)),((8*1.14)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar78]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=(5*1.14)R
Y=202
Shape=Rectangle 0,0,(8*1.14),(-(202-(8*1.14))*[MeasureAudioSmoothed78]-(8*1.14)),((8*1.14)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar79]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=(5*1.14)R
Y=202
Shape=Rectangle 0,0,(8*1.14),(-(202-(8*1.14))*[MeasureAudioSmoothed79]-(8*1.14)),((8*1.14)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar80]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=(5*1.14)R
Y=202
Shape=Rectangle 0,0,(8*1.14),(-(202-(8*1.14))*[MeasureAudioSmoothed80]-(8*1.14)),((8*1.14)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar81]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=(5*1.14)R
Y=202
Shape=Rectangle 0,0,(8*1.14),(-(202-(8*1.14))*[MeasureAudioSmoothed81]-(8*1.14)),((8*1.14)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar82]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=(5*1.14)R
Y=202
Shape=Rectangle 0,0,(8*1.14),(-(202-(8*1.14))*[MeasureAudioSmoothed82]-(8*1.14)),((8*1.14)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar83]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=(5*1.14)R
Y=202
Shape=Rectangle 0,0,(8*1.14),(-(202-(8*1.14))*[MeasureAudioSmoothed83]-(8*1.14)),((8*1.14)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar84]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=(5*1.14)R
Y=202
Shape=Rectangle 0,0,(8*1.14),(-(202-(8*1.14))*[MeasureAudioSmoothed84]-(8*1.14)),((8*1.14)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar85]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=(5*1.14)R
Y=202
Shape=Rectangle 0,0,(8*1.14),(-(202-(8*1.14))*[MeasureAudioSmoothed85]-(8*1.14)),((8*1.14)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar86]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=(5*1.14)R
Y=202
Shape=Rectangle 0,0,(8*1.14),(-(202-(8*1.14))*[MeasureAudioSmoothed86]-(8*1.14)),((8*1.14)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar87]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=(5*1.14)R
Y=202
Shape=Rectangle 0,0,(8*1.14),(-(202-(8*1.14))*[MeasureAudioSmoothed87]-(8*1.14)),((8*1.14)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar88]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=(5*1.14)R
Y=202
Shape=Rectangle 0,0,(8*1.14),(-(202-(8*1.14))*[MeasureAudioSmoothed88]-(8*1.14)),((8*1.14)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar89]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=(5*1.14)R
Y=202
Shape=Rectangle 0,0,(8*1.14),(-(202-(8*1.14))*[MeasureAudioSmoothed89]-(8*1.14)),((8*1.14)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar90]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=(5*1.14)R
Y=202
Shape=Rectangle 0,0,(8*1.14),(-(202-(8*1.14))*[MeasureAudioSmoothed90]-(8*1.14)),((8*1.14)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar91]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=(5*1.14)R
Y=202
Shape=Rectangle 0,0,(8*1.14),(-(202-(8*1.14))*[MeasureAudioSmoothed91]-(8*1.14)),((8*1.14)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar92]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=(5*1.14)R
Y=202
Shape=Rectangle 0,0,(8*1.14),(-(202-(8*1.14))*[MeasureAudioSmoothed92]-(8*1.14)),((8*1.14)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar93]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=(5*1.14)R
Y=202
Shape=Rectangle 0,0,(8*1.14),(-(202-(8*1.14))*[MeasureAudioSmoothed93]-(8*1.14)),((8*1.14)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar94]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=(5*1.14)R
Y=202
Shape=Rectangle 0,0,(8*1.14),(-(202-(8*1.14))*[MeasureAudioSmoothed94]-(8*1.14)),((8*1.14)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar95]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=(5*1.14)R
Y=202
Shape=Rectangle 0,0,(8*1.14),(-(202-(8*1.14))*[MeasureAudioSmoothed95]-(8*1.14)),((8*1.14)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar96]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=(5*1.14)R
Y=202
Shape=Rectangle 0,0,(8*1.14),(-(202-(8*1.14))*[MeasureAudioSmoothed96]-(8*1.14)),((8*1.14)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar97]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=(5*1.14)R
Y=202
Shape=Rectangle 0,0,(8*1.14),(-(202-(8*1.14))*[MeasureAudioSmoothed97]-(8*1.14)),((8*1.14)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar98]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=(5*1.14)R
Y=202
Shape=Rectangle 0,0,(8*1.14),(-(202-(8*1.14))*[MeasureAudioSmoothed98]-(8*1.14)),((8*1.14)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar99]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=(5*1.14)R
Y=202
Shape=Rectangle 0,0,(8*1.14),(-(202-(8*1.14))*[MeasureAudioSmoothed99]-(8*1.14)),((8*1.14)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1